#!/bin/busybox sh

/bin/busybox echo "Creating symlinks for busybox applets..."
/bin/busybox ln -s /bin/busybox /bin/ln

ln -s /bin/busybox /bin/acpid
ln -s /bin/busybox /bin/add-shell
ln -s /bin/busybox /bin/addgroup
ln -s /bin/busybox /bin/adduser
ln -s /bin/busybox /bin/adjtimex
ln -s /bin/busybox /bin/ash
ln -s /bin/busybox /bin/awk
ln -s /bin/busybox /bin/base64
ln -s /bin/busybox /bin/basename
ln -s /bin/busybox /bin/beep
ln -s /bin/busybox /bin/blkid
ln -s /bin/busybox /bin/blockdev
ln -s /bin/busybox /bin/bootchartd
ln -s /bin/busybox /bin/bunzip2
ln -s /bin/busybox /bin/bzcat
ln -s /bin/busybox /bin/bzip2
ln -s /bin/busybox /bin/cal
ln -s /bin/busybox /bin/cat
ln -s /bin/busybox /bin/catv
ln -s /bin/busybox /bin/chat
ln -s /bin/busybox /bin/chattr
ln -s /bin/busybox /bin/chgrp
ln -s /bin/busybox /bin/chmod
ln -s /bin/busybox /bin/chown
ln -s /bin/busybox /bin/chpasswd
ln -s /bin/busybox /bin/chpst
ln -s /bin/busybox /bin/chroot
ln -s /bin/busybox /bin/chrt
ln -s /bin/busybox /bin/cksum
ln -s /bin/busybox /bin/clear
ln -s /bin/busybox /bin/cmp
ln -s /bin/busybox /bin/comm
ln -s /bin/busybox /bin/conspy
ln -s /bin/busybox /bin/cp
ln -s /bin/busybox /bin/cpio
ln -s /bin/busybox /bin/crond
ln -s /bin/busybox /bin/crontab
ln -s /bin/busybox /bin/cryptpw
ln -s /bin/busybox /bin/cttyhack
ln -s /bin/busybox /bin/cut
ln -s /bin/busybox /bin/date
ln -s /bin/busybox /bin/dc
ln -s /bin/busybox /bin/dd
ln -s /bin/busybox /bin/deallocvt
ln -s /bin/busybox /bin/delgroup
ln -s /bin/busybox /bin/deluser
ln -s /bin/busybox /bin/depmod
ln -s /bin/busybox /bin/devmem
ln -s /bin/busybox /bin/df
ln -s /bin/busybox /bin/dhcprelay
ln -s /bin/busybox /bin/diff
ln -s /bin/busybox /bin/dirname
ln -s /bin/busybox /bin/dmesg
ln -s /bin/busybox /bin/dnsd
ln -s /bin/busybox /bin/dnsdomainname
ln -s /bin/busybox /bin/dos2unix
ln -s /bin/busybox /bin/du
ln -s /bin/busybox /bin/dumpleases
ln -s /bin/busybox /bin/echo
ln -s /bin/busybox /bin/ed
ln -s /bin/busybox /bin/egrep
ln -s /bin/busybox /bin/eject
ln -s /bin/busybox /bin/env
ln -s /bin/busybox /bin/envdir
ln -s /bin/busybox /bin/envuidgid
ln -s /bin/busybox /bin/expand
ln -s /bin/busybox /bin/expr
ln -s /bin/busybox /bin/false
ln -s /bin/busybox /bin/fbset
ln -s /bin/busybox /bin/fbsplash
ln -s /bin/busybox /bin/fdflush
ln -s /bin/busybox /bin/fdformat
ln -s /bin/busybox /bin/fdisk
ln -s /bin/busybox /bin/fgconsole
ln -s /bin/busybox /bin/fgrep
ln -s /bin/busybox /bin/find
ln -s /bin/busybox /bin/findfs
ln -s /bin/busybox /bin/flock
ln -s /bin/busybox /bin/fold
ln -s /bin/busybox /bin/free
ln -s /bin/busybox /bin/freeramdisk
ln -s /bin/busybox /bin/fsck
ln -s /bin/busybox /bin/fsck.minix
ln -s /bin/busybox /bin/fsync
ln -s /bin/busybox /bin/getopt
ln -s /bin/busybox /bin/getty
ln -s /bin/busybox /bin/grep
ln -s /bin/busybox /bin/groups
ln -s /bin/busybox /bin/gunzip
ln -s /bin/busybox /bin/gzip
ln -s /bin/busybox /bin/halt
ln -s /bin/busybox /bin/hd
ln -s /bin/busybox /bin/hdparm
ln -s /bin/busybox /bin/head
ln -s /bin/busybox /bin/hexdump
ln -s /bin/busybox /bin/hostid
ln -s /bin/busybox /bin/hostname
ln -s /bin/busybox /bin/hush
ln -s /bin/busybox /bin/hwclock
ln -s /bin/busybox /bin/id
ln -s /bin/busybox /bin/ifconfig
ln -s /bin/busybox /bin/ifdown
ln -s /bin/busybox /bin/ifup
ln -s /bin/busybox /bin/init
ln -s /bin/busybox /bin/insmod
ln -s /bin/busybox /bin/install
ln -s /bin/busybox /bin/ionice
ln -s /bin/busybox /bin/iostat
ln -s /bin/busybox /bin/ip
ln -s /bin/busybox /bin/ipaddr
ln -s /bin/busybox /bin/ipcalc
ln -s /bin/busybox /bin/ipcrm
ln -s /bin/busybox /bin/ipcs
ln -s /bin/busybox /bin/iplink
ln -s /bin/busybox /bin/iprule
ln -s /bin/busybox /bin/iptunnel
ln -s /bin/busybox /bin/kbd_mode
ln -s /bin/busybox /bin/kill
ln -s /bin/busybox /bin/killall
ln -s /bin/busybox /bin/killall5
ln -s /bin/busybox /bin/klogd
ln -s /bin/busybox /bin/last
ln -s /bin/busybox /bin/less
ln -s /bin/busybox /bin/linux32
ln -s /bin/busybox /bin/linux64
ln -s /bin/busybox /bin/linuxrc
ln -s /bin/busybox /bin/loadfont
ln -s /bin/busybox /bin/loadkmap
ln -s /bin/busybox /bin/logger
ln -s /bin/busybox /bin/login
ln -s /bin/busybox /bin/logname
ln -s /bin/busybox /bin/logread
ln -s /bin/busybox /bin/losetup
ln -s /bin/busybox /bin/lpd
ln -s /bin/busybox /bin/lpq
ln -s /bin/busybox /bin/lpr
ln -s /bin/busybox /bin/ls
ln -s /bin/busybox /bin/lsattr
ln -s /bin/busybox /bin/lsmod
ln -s /bin/busybox /bin/lsof
ln -s /bin/busybox /bin/lzcat
ln -s /bin/busybox /bin/lzma
ln -s /bin/busybox /bin/lzop
ln -s /bin/busybox /bin/lzopcat
ln -s /bin/busybox /bin/makedevs
ln -s /bin/busybox /bin/makemime
ln -s /bin/busybox /bin/man
ln -s /bin/busybox /bin/md5sum
ln -s /bin/busybox /bin/mdev
ln -s /bin/busybox /bin/mesg
ln -s /bin/busybox /bin/microcom
ln -s /bin/busybox /bin/mkdir
ln -s /bin/busybox /bin/mkdosfs
ln -s /bin/busybox /bin/mke2fs
ln -s /bin/busybox /bin/mkfifo
ln -s /bin/busybox /bin/mkfs.ext2
ln -s /bin/busybox /bin/mkfs.minix
ln -s /bin/busybox /bin/mkfs.vfat
ln -s /bin/busybox /bin/mknod
ln -s /bin/busybox /bin/mkpasswd
ln -s /bin/busybox /bin/mkswap
ln -s /bin/busybox /bin/mktemp
ln -s /bin/busybox /bin/modinfo
ln -s /bin/busybox /bin/modprobe
ln -s /bin/busybox /bin/more
ln -s /bin/busybox /bin/mount
ln -s /bin/busybox /bin/mpstat
ln -s /bin/busybox /bin/mt
ln -s /bin/busybox /bin/mv
ln -s /bin/busybox /bin/nanddump
ln -s /bin/busybox /bin/nandwrite
ln -s /bin/busybox /bin/nc
ln -s /bin/busybox /bin/netstat
ln -s /bin/busybox /bin/nice
ln -s /bin/busybox /bin/nmeter
ln -s /bin/busybox /bin/nohup
ln -s /bin/busybox /bin/nslookup
ln -s /bin/busybox /bin/ntpd
ln -s /bin/busybox /bin/od
ln -s /bin/busybox /bin/openvt
ln -s /bin/busybox /bin/passwd
ln -s /bin/busybox /bin/patch
ln -s /bin/busybox /bin/pgrep
ln -s /bin/busybox /bin/pidof
ln -s /bin/busybox /bin/ping
ln -s /bin/busybox /bin/pipe_progress
ln -s /bin/busybox /bin/pivot_root
ln -s /bin/busybox /bin/pkill
ln -s /bin/busybox /bin/pmap
ln -s /bin/busybox /bin/popmaildir
ln -s /bin/busybox /bin/poweroff
ln -s /bin/busybox /bin/powertop
ln -s /bin/busybox /bin/printf
ln -s /bin/busybox /bin/ps
ln -s /bin/busybox /bin/pscan
ln -s /bin/busybox /bin/pstree
ln -s /bin/busybox /bin/pwd
ln -s /bin/busybox /bin/pwdx
ln -s /bin/busybox /bin/raidautorun
ln -s /bin/busybox /bin/rdate
ln -s /bin/busybox /bin/rdev
ln -s /bin/busybox /bin/readahead
ln -s /bin/busybox /bin/readlink
ln -s /bin/busybox /bin/readprofile
ln -s /bin/busybox /bin/realpath
ln -s /bin/busybox /bin/reboot
ln -s /bin/busybox /bin/reformime
ln -s /bin/busybox /bin/remove-shell
ln -s /bin/busybox /bin/renice
ln -s /bin/busybox /bin/reset
ln -s /bin/busybox /bin/resize
ln -s /bin/busybox /bin/rev
ln -s /bin/busybox /bin/rm
ln -s /bin/busybox /bin/rmdir
ln -s /bin/busybox /bin/rmmod
ln -s /bin/busybox /bin/route
ln -s /bin/busybox /bin/rpm
ln -s /bin/busybox /bin/rpm2cpio
ln -s /bin/busybox /bin/run-parts
ln -s /bin/busybox /bin/runlevel
ln -s /bin/busybox /bin/runsv
ln -s /bin/busybox /bin/runsvdir
ln -s /bin/busybox /bin/rx
ln -s /bin/busybox /bin/script
ln -s /bin/busybox /bin/scriptreplay
ln -s /bin/busybox /bin/sed
ln -s /bin/busybox /bin/sendmail
ln -s /bin/busybox /bin/seq
ln -s /bin/busybox /bin/setarch
ln -s /bin/busybox /bin/setconsole
ln -s /bin/busybox /bin/setfont
ln -s /bin/busybox /bin/setkeycodes
ln -s /bin/busybox /bin/setlogcons
ln -s /bin/busybox /bin/setserial
ln -s /bin/busybox /bin/setsid
ln -s /bin/busybox /bin/setuidgid
ln -s /bin/busybox /bin/sh
ln -s /bin/busybox /bin/sha1sum
ln -s /bin/busybox /bin/sha256sum
ln -s /bin/busybox /bin/sha3sum
ln -s /bin/busybox /bin/sha512sum
ln -s /bin/busybox /bin/slattach
ln -s /bin/busybox /bin/sleep
ln -s /bin/busybox /bin/smemcap
ln -s /bin/busybox /bin/softlimit
ln -s /bin/busybox /bin/sort
ln -s /bin/busybox /bin/split
ln -s /bin/busybox /bin/start-stop-daemon
ln -s /bin/busybox /bin/stat
ln -s /bin/busybox /bin/strings
ln -s /bin/busybox /bin/stty
ln -s /bin/busybox /bin/su
ln -s /bin/busybox /bin/sulogin
ln -s /bin/busybox /bin/sum
ln -s /bin/busybox /bin/sv
ln -s /bin/busybox /bin/svlogd
ln -s /bin/busybox /bin/swapoff
ln -s /bin/busybox /bin/swapon
ln -s /bin/busybox /bin/switch_root
ln -s /bin/busybox /bin/sync
ln -s /bin/busybox /bin/sysctl
ln -s /bin/busybox /bin/syslogd
ln -s /bin/busybox /bin/tac
ln -s /bin/busybox /bin/tail
ln -s /bin/busybox /bin/tar
ln -s /bin/busybox /bin/tcpsvd
ln -s /bin/busybox /bin/tee
ln -s /bin/busybox /bin/telnet
ln -s /bin/busybox /bin/test
ln -s /bin/busybox /bin/tftp
ln -s /bin/busybox /bin/tftpd
ln -s /bin/busybox /bin/time
ln -s /bin/busybox /bin/timeout
ln -s /bin/busybox /bin/top
ln -s /bin/busybox /bin/touch
ln -s /bin/busybox /bin/tr
ln -s /bin/busybox /bin/traceroute
ln -s /bin/busybox /bin/true
ln -s /bin/busybox /bin/tty
ln -s /bin/busybox /bin/ttysize
ln -s /bin/busybox /bin/tunctl
ln -s /bin/busybox /bin/ubiattach
ln -s /bin/busybox /bin/ubidetach
ln -s /bin/busybox /bin/ubimkvol
ln -s /bin/busybox /bin/ubirmvol
ln -s /bin/busybox /bin/ubirsvol
ln -s /bin/busybox /bin/ubiupdatevol
ln -s /bin/busybox /bin/udhcpc
ln -s /bin/busybox /bin/udhcpd
ln -s /bin/busybox /bin/udpsvd
ln -s /bin/busybox /bin/umount
ln -s /bin/busybox /bin/uname
ln -s /bin/busybox /bin/unexpand
ln -s /bin/busybox /bin/uniq
ln -s /bin/busybox /bin/unlzma
ln -s /bin/busybox /bin/unlzop
ln -s /bin/busybox /bin/unxz
ln -s /bin/busybox /bin/unzip
ln -s /bin/busybox /bin/uptime
ln -s /bin/busybox /bin/users
ln -s /bin/busybox /bin/usleep
ln -s /bin/busybox /bin/uudecode
ln -s /bin/busybox /bin/uuencode
ln -s /bin/busybox /bin/vconfig
ln -s /bin/busybox /bin/vi
ln -s /bin/busybox /bin/vlock
ln -s /bin/busybox /bin/volname
ln -s /bin/busybox /bin/wall
ln -s /bin/busybox /bin/watch
ln -s /bin/busybox /bin/watchdog
ln -s /bin/busybox /bin/wc
ln -s /bin/busybox /bin/wget
ln -s /bin/busybox /bin/which
ln -s /bin/busybox /bin/who
ln -s /bin/busybox /bin/whoami
ln -s /bin/busybox /bin/xargs
ln -s /bin/busybox /bin/xz
ln -s /bin/busybox /bin/xzcat
ln -s /bin/busybox /bin/yes
ln -s /bin/busybox /bin/zcat
ln -s /bin/busybox /bin/zcip
