#!/bin/busybox sh

/bin/busybox sh /busyboxinit.sh

mount -t proc proc proc
mount -t sysfs sys sys
mdev -s

ifconfig eth0 up
udhcpc -i eth0 -s /etc/udhcpc.script

clear
echo "Welcome to the Fast Linux Deployment Toolkit"

sh /imaging.sh
sh
#drop to shell
#setsid sh -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
