#!/bin/sh
#  Copyright 2013 Andrew Lobos and Penn Manor School District
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

IMAGING_SERVER="10.0.0.1"
MACADDR=`ifconfig | grep "eth0" | tr -s ' ' | cut -d ' ' -f5`
wget -O hostname http://$IMAGING_SERVER/api/hostname?mac=$MACADDR 2> /dev/null
wget -O currentImage http://$IMAGING_SERVER/api/currentImage 2> /dev/null
HOSTNAME="`cat hostname`"
IMAGE_NAME="`cat currentImage`"

echo "I am $HOSTNAME with MAC address $MACADDR"

mount -t nfs4 $IMAGING_SERVER:/images /nfs

dd if=/nfs/$IMAGE_NAME/mbr.bin of=/dev/sda bs=512 count=1


hdparm -z /dev/sda
mdev -s

for f in `find /nfs/$IMAGE_NAME/sd* -type f | sort -nr`
do
	echo "Restoring $f"
	udp-receiver | partclone.extfs -r -s - -o /dev/`basename $f` -L /partclone.log
done


# Setup mnt enviorment for chroots
mount /dev/sda1 /mnt

sh /nfs/$IMAGE_NAME/postimage.sh $HOSTNAME

# Reset network rules
rm -f /mnt/etc/udev/rules.d/70-persistent-net.rules

# Reinstall GRUB in chroot
sh /fixGrub.sh

umount /mnt