#!/bin/sh
#  Copyright 2013 Andrew Lobos and Penn Manor School District
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

IMAGING_SERVER="10.0.0.1"

mkdir nfs
mount -t nfs4 $IMAGING_SERVER:/images nfs

echo -n "Enter a name for this image: "
read IMAGENAME

echo "This image will be saved as $IMAGENAME"
mkdir /nfs/$IMAGENAME

echo "Copying MBR"
dd if=/dev/sda of=/nfs/$IMAGENAME/mbr.bin bs=512 count=1
echo "Done"

while :
do
	echo "Enter the name of the device that you would like to copy or type exit to finish imaging."
	echo "Available devices are"
	for f in `find /dev/sd*`
	do
		echo -n "`basename $f` "
	done
	echo ""
	
	echo -n "Device: "
	read DEVNAME
	
	if [ "$DEVNAME" == "exit" ]; then
		break
	fi
	
	partclone.extfs -c -s /dev/$DEVNAME -o /nfs/$IMAGENAME/$DEVNAME -L log
done

echo "Done Imaging"